{"name": "test2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 1\n  +2\n  -1", "trace": "self = <test_case.test_weather_condition.TestWeatherCondition object at 0x109b85780>\n\n    def test2(self):\n>       assert 2 == 1\nE       assert 2 == 1\nE         +2\nE         -1\n\ntest_case/test_weather_condition.py:50: AssertionError"}, "start": 1585153780377, "stop": 1585153780378, "uuid": "db54ad4b-f0e5-465d-8a2c-da5ff00c8f11", "historyId": "3f9bf41955f208347948ea1486ce3359", "fullName": "test_case.test_weather_condition.TestWeatherCondition#test2", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_weather_condition"}, {"name": "subSuite", "value": "TestWeatherCondition"}, {"name": "host", "value": "liqingMacBook-Pro.local"}, {"name": "thread", "value": "31868-Thread-2"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_weather_condition"}]}