<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="liqingMacBook-Pro.local" name="pytest" skipped="0" tests="2" time="52.006" timestamp="2020-03-25T21:07:14.903744"><testcase classname="test_case.test_weather_condition.TestWeatherCondition" file="test_case/test_weather_condition.py" line="24" name="test_weather_desc_equal" time="31.254"></testcase><testcase classname="test_case.test_weather_condition.TestWeatherCondition" file="test_case/test_weather_condition.py" line="35" name="test_temp_equal" time="17.543"><failure message="assert False">self = &lt;test_case.test_weather_condition.TestWeatherCondition object at 0x109b73a58&gt;
browser = &lt;appium.webdriver.webdriver.WebDriver (session=&quot;61dfd340-a2b3-4949-a450-f5601406a549&quot;)&gt;

    def test_temp_equal(self, browser):
        browser.launch_app()
        self.weather_condition_business = WeatherCompareBusiness(browser)
        result = self.weather_condition_business.compare_temp()
        print(&quot;result&quot;, result)
&gt;       assert result
E       assert False

test_case/test_weather_condition.py:41: AssertionError</failure></testcase></testsuite></testsuites>