<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="liqingMacBook-Pro.local" name="pytest" skipped="0" tests="2" time="74.022" timestamp="2020-03-25T20:55:33.131831"><testcase classname="test_case.test_weather_condition.TestWeatherCondition" file="test_case/test_weather_condition.py" line="24" name="test_weather_desc_equal" time="30.891"></testcase><testcase classname="test_case.test_weather_condition.TestWeatherCondition" file="test_case/test_weather_condition.py" line="35" name="test_temp_equal" time="36.235"><failure message="assert False">self = &lt;test_case.test_weather_condition.TestWeatherCondition object at 0x109c85a20&gt;
browser = &lt;appium.webdriver.webdriver.WebDriver (session=&quot;7a05efd2-7d58-47ee-bd27-a814dc9633d0&quot;)&gt;

    def test_temp_equal(self, browser):
        browser.launch_app()
        self.weather_condition_business = WeatherCompareBusiness(browser)
        result = self.weather_condition_business.compare_temp()
        print(&quot;result&quot;, result)
&gt;       assert result
E       assert False

test_case/test_weather_condition.py:41: AssertionError</failure></testcase></testsuite></testsuites>